
["Village Spawning"]
	#Defines number of generated structures per 1 000 000 chunks
	"General Village Spawning" = 750.0
	#Defines number of generated structures per 1 000 000 chunks
	"Desert Village Spawning" = 1000.0
	#Defines number of generated structures per 1 000 000 chunks
	"Snowy Village Spawning" = 1500.0

